version: '3'
services:
  influx:
    image: influxdb:1.8-alpine
    environment:
      INFLUXDB_DB: "mydb"
      INFLUXDB_USER: "my_user"
      INFLUXDB_USER_PASSWORD: "my_pass"
  influx-passwordless:
    image: influxdb:1.8-alpine
    environment:
      INFLUXDB_DB: "mydb"
      INFLUXDB_USER: "my_user"
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
  graphite:
    image: graphiteapp/graphite-statsd
    environment:
      REDIS_TAGDB: "y"
  timescale:
    build:
      dockerfile: ci/Dockerfile.timescale
      context: .
    environment:
      POSTGRES_PASSWORD: 123456
  app:
    build:
      dockerfile: ci/Dockerfile.tests
      context: .
    privileged: true
    depends_on:
      - timescale
      - graphite
      - influx
    command: ./ci/wait-for-it.sh timescale:5432 -- ./ci/wait-for-it.sh influx:8086 -- ./ci/wait-for-it.sh graphite:2003 -- ./ci/wait-for-it.sh graphite:8080 -- ./ci/wait-for-it.sh graphite:80 -- mono /root/.nuget/packages/xunit.runner.console/2.4.1/tools/net461/xunit.console.exe OhmGraphite.Test/bin/Debug/net461/OhmGraphite.Test.dll
